routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('/', 'PagesController@index');

Auth::routes();

Route::group(['middleware' => 'auth'], function () {
    Route::get('/dashboard', 'DashboardController@index');

    Route::get('jobs/{job}/xml', 'JobsController@showXml');
    Route::get('jobs/{job}/pdf', 'JobsController@showPdf');
    Route::resource('jobs', 'JobsController');

    Route::get('customers/{customer}/barcode', function (App\Customer $customer) {
        $barcodeOptions = [
            'text' => str_pad($customer->id, 12, '0', STR_PAD_LEFT),
            'barHeight' => 100,
            'barThickWidth' => 4,
            'barThinWidth' => 2,
        ];

        // No required options.
        $rendererOptions = [
            'barHeight' => 100,
        ];

        // Draw the barcode, capturing the resource:
        $renderer = \Zend\Barcode\Barcode::factory(
            'ean13',
            'image',
            $barcodeOptions,
            $rendererOptions
        );
        return new \Illuminate\Http\Response($renderer->render(), 200, ['Content-Type' => 'image/png']);
    });
    Route::resource('customers', 'CustomersController');
    Route::resource('vehicles', 'VehiclesController');
    Route::resource('services', 'ServicesController');
});

app/Service.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Service extends Model
{
    protected $fillable = ['name', 'price'];
}

app/Http/Controllers/ServicesController.php
<?php

namespace App\Http\Controllers;

use App\Service;
use Illuminate\Http\Request;

use App\Http\Requests;

class ServicesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $services = Service::paginate();

        return view('services.index', compact('services'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('services.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Service::create($request->all());

        return redirect()->route('services.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/services/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="card card-block mt-1">
                    <h3 class="card-title">Novo Serviço</h3>

                    <div class="card-title row">
                        <form action="{{ route('services.store') }}" method="post" class="col-md-6 offset-md-3">

                            {{ csrf_field() }}

                            <div class="form-group{{ $errors->has('name') ? ' has-danger' : '' }}">
                                <label for="name" class="col-form-label">Descrição</label>
                                <input type="text" id="name" name="name" class="form-control">
                                @if ($errors->has('name'))
                                    <span class="help-block">{{ $errors->first('name') }}</span>
                                @endif
                            </div>

                            <div class="form-group{{ $errors->has('price') ? ' has-danger' : '' }}">
                                <label for="price">Valor</label>
                                <input type="text" id="price" name="price" class="form-control" required>
                                @if ($errors->has('plate'))
                                    <span class="help-block">{{ $errors->first('plate') }}</span>
                                @endif
                            </div>

                            <button class="btn btn-default">Adicionar</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/services/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="card card-block mt-1">
                    <h3 class="card-title">Serviços</h3>

                    <p>
                        <a href="{{ route('services.create') }}">Novo Serviço</a>
                    </p>

                    <div class="card-text">
                        @if ($services->count())
                            <table class="table">
                                <thead>
                                <tr>
                                    <th>Descrição</th>
                                    <th>Preço</th>
                                    <th>Ações</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach ($services as $service)
                                    <tr>
                                        <td>{{ $service->name }}</td>
                                        <td>R$ {{ $service->price }}</td>
                                        <td>
                                            <a href="{{ route('services.show', $service) }}">
                                                Ver serviço
                                            </a>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        @else
                            <p class="p-3 text-xs-center">Nenhum serviço cadastrado ainda</p>
                        @endif

                        {{ $services->links('pagination::bootstrap-4') }}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection