routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('/', 'PagesController@index');

Auth::routes();

Route::group(['middleware' => 'auth'], function () {
    Route::get('/dashboard', 'DashboardController@index');

    Route::get('jobs/{job}/xml', 'JobsController@showXml');
    Route::get('jobs/{job}/pdf', 'JobsController@showPdf');
    Route::resource('jobs', 'JobsController');

    Route::get('customers/{customer}/barcode', function (App\Customer $customer) {
        $barcodeOptions = [
            'text' => str_pad($customer->id, 12, '0', STR_PAD_LEFT),
            'barHeight' => 100,
            'barThickWidth' => 4,
            'barThinWidth' => 2,
        ];

        // No required options.
        $rendererOptions = [
            'barHeight' => 100,
        ];

        // Draw the barcode, capturing the resource:
        $renderer = \Zend\Barcode\Barcode::factory(
            'ean13',
            'image',
            $barcodeOptions,
            $rendererOptions
        );
        return new \Illuminate\Http\Response($renderer->render(), 200, ['Content-Type' => 'image/png']);
    });
    Route::resource('customers', 'CustomersController');
    Route::resource('vehicles', 'VehiclesController');
    Route::resource('services', 'ServicesController');
});

app/Vehicle.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Vehicle extends Model
{
    protected $fillable = [ 'customer_id', 'plate', 'model', 'year' ];

    public function owner()
    {
    	return $this->belongsTo(Customer::class, 'customer_id');
    }
}

app/Http/Controllers/VehiclesController.php
<?php

namespace App\Http\Controllers;

use App\Customer;
use App\Http\Requests\StoreVehicleRequest;
use App\Vehicle;
use App\Http\Requests;
use Illuminate\Http\Request;

class VehiclesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $vehicles = Vehicle::with('owner')->paginate();

        return view('vehicles.index', compact('vehicles'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $customers = Customer::all();

        return view('vehicles.create', compact('customers'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreVehicleRequest $request)
    {
        Vehicle::create($request->all());

        return redirect()->route('vehicles.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/vehicles/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="card card-block mt-1">
                    <h3 class="card-title">Novo Veículo</h3>

                    <div class="card-title row">
                        <form action="{{ route('vehicles.store') }}" method="post" class="col-md-6 offset-md-3">

                            {{ csrf_field() }}

                            <div class="form-group{{ $errors->has('customer_id') ? ' has-error' : '' }}">
                                <label for="customer_id" class="control-label">Cliente</label>
                                <select id="customer_id" name="customer_id" class="form-control">
                                    <option value="" disabled selected>Sem cliente</option>
                                    @foreach($customers as $customer)
                                        <option value="{{ $customer->id }}">{{ $customer->name }}</option>
                                    @endforeach
                                </select>
                                @if ($errors->has('name'))
                                    <span class="help-block">{{ $errors->first('name') }}</span>
                                @endif
                            </div>

                            <div class="form-group{{ $errors->has('model') ? ' has-danger' : '' }}">
                                <label for="model" class="col-form-label">Modelo</label>
                                <input type="text" id="model" name="model" class="form-control">
                                @if ($errors->has('model'))
                                    <span class="help-block">{{ $errors->first('model') }}</span>
                                @endif
                            </div>

                            <div class="form-group{{ $errors->has('plate') ? ' has-danger' : '' }}">
                                <label for="plate">Placa</label>
                                <input type="text" id="plate" name="plate" class="form-control" pattern="[A-Z]{3}-[0-9]{4}" required>
                                @if ($errors->has('plate'))
                                    <span class="help-block">{{ $errors->first('plate') }}</span>
                                @endif
                            </div>

                            <div class="form-group{{ $errors->has('year') ? ' has-error' : '' }}">
                                <label for="year">Ano</label>
                                <select name="year" id="year" class="form-control">
                                    @foreach (range(date("Y"), date("Y") - 60) as $year)
                                        <option value="{{ $year }}">{{ $year }}</option>
                                    @endforeach
                                </select>
                                @if ($errors->has('year'))
                                    <span class="help-block">{{ $errors->first('year') }}</span>
                                @endif
                            </div>

                            <button class="btn btn-default">Adicionar</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/vehicles/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="card card-block mt-1">
                    <h3 class="card-title">Veículos</h3>

                    <p>
                        <a href="{{ route('vehicles.create') }}">Novo Veículo</a>
                    </p>

                    <div class="card-text">
                        @if ($vehicles->count())
                            <table class="table">
                                <thead>
                                <tr>
                                    <th>Cliente</th>
                                    <th>Modelo</th>
                                    <th>Placa</th>
                                    <th>Ano</th>
                                    <th>Ações</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach ($vehicles as $vehicle)
                                    <tr>
                                        <td>
                                            @if ($vehicle->owner)
                                                <a href="{{ route('customers.show', $vehicle->owner) }}">
                                                    {{ $vehicle->owner->name }}
                                                </a>
                                            @else
                                                Sem cliente associado
                                            @endif
                                        </td>
                                        <td>{{ $vehicle->model }}</td>
                                        <td>{{ $vehicle->plate }}</td>
                                        <td>{{ $vehicle->year }}</td>
                                        <td>
                                            <a href="{{ route('vehicles.show', $vehicle) }}">
                                                Ver veículo
                                            </a>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        @else
                            <p class="p-3 text-xs-center">Nenhum veículo cadastrado ainda</p>
                        @endif

                        {{ $vehicles->links('pagination::bootstrap-4') }}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection