routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('/', 'PagesController@index');

Auth::routes();

Route::group(['middleware' => 'auth'], function () {
    Route::get('/dashboard', 'DashboardController@index');

    Route::get('jobs/{job}/xml', 'JobsController@showXml');
    Route::get('jobs/{job}/pdf', 'JobsController@showPdf');
    Route::resource('jobs', 'JobsController');

    Route::get('customers/{customer}/barcode', function (App\Customer $customer) {
        $barcodeOptions = [
            'text' => str_pad($customer->id, 12, '0', STR_PAD_LEFT),
            'barHeight' => 100,
            'barThickWidth' => 4,
            'barThinWidth' => 2,
        ];

        // No required options.
        $rendererOptions = [
            'barHeight' => 100,
        ];

        // Draw the barcode, capturing the resource:
        $renderer = \Zend\Barcode\Barcode::factory(
            'ean13',
            'image',
            $barcodeOptions,
            $rendererOptions
        );
        return new \Illuminate\Http\Response($renderer->render(), 200, ['Content-Type' => 'image/png']);
    });
    Route::resource('customers', 'CustomersController');
    Route::resource('vehicles', 'VehiclesController');
    Route::resource('services', 'ServicesController');
});

app/Job.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Job extends Model
{
    protected $fillable = [ 'service_id', 'vehicle_id' ];

    public function service()
    {
        return $this->belongsTo(Service::class);
    }

    public function vehicle()
    {
        return $this->belongsTo(Vehicle::class);
    }
}

app/Http/Controllers/JobsController.php
<?php

namespace App\Http\Controllers;

use App\Job;
use Illuminate\Http\Request;

use App\Http\Requests;
use NFePHP\Common\Files\FilesFolders;
use NFePHP\Extras\Danfe;
use NFePHP\NFe\MakeNFe;
use NFePHP\NFe\ToolsNFe;

class JobsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $jobs = Job::paginate();

        return view('jobs.index', compact('jobs'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $job = Job::create($request->all());

        return redirect()->route('jobs.show', $job);
    }

    /**
     * Display the specified resource.
     *
     * @param Job $job
     * @return \Illuminate\Http\Response
     */
    public function show(Job $job)
    {
        return view('jobs.show', compact('job'));
    }

    /**
     * Display the specified resource.
     *
     * @param Job $job
     * @return \Illuminate\Http\Response
     */
    public function showXml(Job $job)
    {

        $nfe = new MakeNFe();
        $nfeTools = new ToolsNFe(app_path('config.json'));
//Dados da NFe - infNFe
        $cUF = '52'; //codigo numerico do estado
        $cNF = '00000010'; //numero aleatório da NF
        $natOp = 'Prestação de Serviço'; //natureza da operação
        $indPag = '1'; //0=Pagamento à vista; 1=Pagamento a prazo; 2=Outros
        $mod = '55'; //modelo da NFe 55 ou 65 essa última NFCe
        $serie = '1'; //serie da NFe
        $nNF = '10'; // numero da NFe
        $dhEmi = date("Y-m-d H:i:sP");//Formato: “AAAA-MM-DDThh:mm:ssTZD” (UTC - Universal Coordinated Time).
        $dhSaiEnt = date("Y-m-d H:i:sP");//Não informar este campo para a NFC-e.
        $tpNF = '1';
        $idDest = '1'; //1=Operação interna; 2=Operação interestadual; 3=Operação com exterior.
        $cMunFG = '5200258';
        $tpImp = '1'; //0=Sem geração de DANFE; 1=DANFE normal, Retrato; 2=DANFE normal, Paisagem;
        //3=DANFE Simplificado; 4=DANFE NFC-e; 5=DANFE NFC-e em mensagem eletrônica
        //(o envio de mensagem eletrônica pode ser feita de forma simultânea com a impressão do DANFE;
        //usar o tpImp=5 quando esta for a única forma de disponibilização do DANFE).
        $tpEmis = '1'; //1=Emissão normal (não em contingência);
        //2=Contingência FS-IA, com impressão do DANFE em formulário de segurança;
        //3=Contingência SCAN (Sistema de Contingência do Ambiente Nacional);
        //4=Contingência DPEC (Declaração Prévia da Emissão em Contingência);
        //5=Contingência FS-DA, com impressão do DANFE em formulário de segurança;
        //6=Contingência SVC-AN (SEFAZ Virtual de Contingência do AN);
        //7=Contingência SVC-RS (SEFAZ Virtual de Contingência do RS);
        //9=Contingência off-line da NFC-e (as demais opções de contingência são válidas também para a NFC-e);
        //Nota: Para a NFC-e somente estão disponíveis e são válidas as opções de contingência 5 e 9.
        $tpAmb = '1'; //1=Produção; 2=Homologação
        $finNFe = '1'; //1=NF-e normal; 2=NF-e complementar; 3=NF-e de ajuste; 4=Devolução/Retorno.
        $indFinal = '0'; //0=Normal; 1=Consumidor final;
        $indPres = '9'; //0=Não se aplica (por exemplo, Nota Fiscal complementar ou de ajuste);
        //1=Operação presencial;
        //2=Operação não presencial, pela Internet;
        //3=Operação não presencial, Teleatendimento;
        //4=NFC-e em operação com entrega a domicílio;
        //9=Operação não presencial, outros.
        $procEmi = '0'; //0=Emissão de NF-e com aplicativo do contribuinte;
        //1=Emissão de NF-e avulsa pelo Fisco;
        //2=Emissão de NF-e avulsa, pelo contribuinte com seu certificado digital, através do site do Fisco;
        //3=Emissão NF-e pelo contribuinte com aplicativo fornecido pelo Fisco.
        $verProc = '4.0.43'; //versão do aplicativo emissor
        $dhCont = ''; //entrada em contingência AAAA-MM-DDThh:mm:ssTZD
        $xJust = ''; //Justificativa da entrada em contingência
//Numero e versão da NFe (infNFe)
        $ano = date('y', strtotime($dhEmi));
        $mes = date('m', strtotime($dhEmi));
        $cnpj = $nfeTools->aConfig['cnpj'];
        $chave = $nfe->montaChave($cUF, $ano, $mes, $cnpj, $mod, $serie, $nNF, $tpEmis, $cNF);
        $versao = '3.10';
        $resp = $nfe->taginfNFe($chave, $versao);
        $cDV = substr($chave, -1); //Digito Verificador da Chave de Acesso da NF-e, o DV é calculado com a aplicação do algoritmo módulo 11 (base 2,9) da Chave de Acesso.
//tag IDE
        $resp = $nfe->tagide($cUF, $cNF, $natOp, $indPag, $mod, $serie, $nNF, $dhEmi, $dhSaiEnt, $tpNF, $idDest, $cMunFG, $tpImp, $tpEmis, $cDV, $tpAmb, $finNFe, $indFinal, $indPres, $procEmi, $verProc, $dhCont, $xJust);
//refNFe NFe referenciada
//$refNFe = '12345678901234567890123456789012345678901234';
//$resp = $nfe->tagrefNFe($refNFe);
//refNF Nota Fiscal 1A referenciada
//$cUF = '35';
//$AAMM = '1312';
//$CNPJ = '12345678901234';
//$mod = '1A';
//$serie = '0';
//$nNF = '1234';
//$resp = $nfe->tagrefNF($cUF, $AAMM, $CNPJ, $mod, $serie, $nNF);
//NFPref Nota Fiscal Produtor Rural referenciada
//$cUF = '35';
//$AAMM = '1312';
//$CNPJ = '12345678901234';
//$CPF = '123456789';
//$IE = '123456';
//$mod = '1';
//$serie = '0';
//$nNF = '1234';
//$resp = $nfe->tagrefNFP($cUF, $AAMM, $CNPJ, $CPF, $IE, $mod, $serie, $nNF);
//CTeref CTe referenciada
//$refCTe = '12345678901234567890123456789012345678901234';
//$resp = $nfe->tagrefCTe($refCTe);
//ECFref ECF referenciada
//$mod = '90';
//$nECF = '12243';
//$nCOO = '111';
//$resp = $nfe->tagrefECF($mod, $nECF, $nCOO);
//Dados do emitente - (Importando dados do config.json)
        $CNPJ = $nfeTools->aConfig['cnpj'];
        $CPF = ''; // Utilizado para CPF na nota
        $xNome = $nfeTools->aConfig['razaosocial'];
        $xFant = $nfeTools->aConfig['nomefantasia'];
        $IE = $nfeTools->aConfig['ie'];
        $IEST = $nfeTools->aConfig['iest'];
        $IM = $nfeTools->aConfig['im'];
        $CNAE = $nfeTools->aConfig['cnae'];
        $CRT = $nfeTools->aConfig['regime'];
        $resp = $nfe->tagemit($CNPJ, $CPF, $xNome, $xFant, $IE, $IEST, $IM, $CNAE, $CRT);
//endereço do emitente
        $xLgr = 'Av. Gov. José Pinhais';
        $nro = 's/n';
        $xCpl = 'Qd. 38 Lt. 4,5 e 34';
        $xBairro = 'Jardim Pinheiros I';
        $cMun = '5200258';
        $xMun = 'Porto Alegre';
        $UF = 'RS';
        $CEP = '72910000';
        $cPais = '1058';
        $xPais = 'Brasil';
        $fone = '6239324097';
        $resp = $nfe->tagenderEmit($xLgr, $nro, $xCpl, $xBairro, $cMun, $xMun, $UF, $CEP, $cPais, $xPais, $fone);

//destinatário
        $CNPJ = '23401454000170';
        $CPF = '';
        $idEstrangeiro = '';
        $xNome = 'Caíque de Castro Soares da Silva';
        $indIEDest = '1';
        $IE = '';
        $ISUF = '';
        $IM = '4128095';
        $email = 'caiquecastro@outlook.com';
        $resp = $nfe->tagdest($CNPJ, $CPF, $idEstrangeiro, $xNome, $indIEDest, $IE, $ISUF, $IM, $email);
//Endereço do destinatário
        $xLgr = 'Av. Charles Schinneider';
        $nro = '1001';
        $xCpl = 'apto 12B';
        $xBairro = 'Vila Edmundo';
        $cMun = '5208707';
        $xMun = 'Taubaté';
        $UF = 'SP';
        $CEP = '12040000';
        $cPais = '1058';
        $xPais = 'Brasil';
        $fone = '12 99202-1817';
        $resp = $nfe->tagenderDest($xLgr, $nro, $xCpl, $xBairro, $cMun, $xMun, $UF, $CEP, $cPais, $xPais, $fone);
//Identificação do local de retirada (se diferente do emitente)
//$CNPJ = '12345678901234';
//$CPF = '';
//$xLgr = 'Rua Vanish';
//$nro = '000';
//$xCpl = 'Ghost';
//$xBairro = 'Assombrado';
//$cMun = '3509502';
//$xMun = 'Campinas';
//$UF = 'SP';
//$resp = $nfe->tagretirada($CNPJ, $CPF, $xLgr, $nro, $xCpl, $xBairro, $cMun, $xMun, $UF);
//Identificação do local de Entrega (se diferente do destinatário)
//$CNPJ = '12345678901234';
//$CPF = '';
//$xLgr = 'Viela Mixuruca';
//$nro = '2';
//$xCpl = 'Quabrada do malandro';
//$xBairro = 'Favela Mau Olhado';
//$cMun = '3509502';
//$xMun = 'Campinas';
//$UF = 'SP';
//$resp = $nfe->tagentrega($CNPJ, $CPF, $xLgr, $nro, $xCpl, $xBairro, $cMun, $xMun, $UF);
//Identificação dos autorizados para fazer o download da NFe (somente versão 3.1)
        /*$aAut = array('23401454000170');
        foreach ($aAut as $aut) {
            if (strlen($aut) == 14) {
                $resp = $nfe->tagautXML($aut);
            } else {
                $resp = $nfe->tagautXML('', $aut);
            }
        }*/
//produtos 1 (Limite da API é de 56 itens por Nota)
        $aP[] = array(
            'nItem' => 1,
            'cProd' => '15',
            'cEAN' => '97899072659522',
            'xProd' => 'Lavagem Completa - Carro Médio',
            'NCM' => '22030000',
            'EXTIPI' => '',
            'CFOP' => '5101',
            'uCom' => 'Un',
            'qCom' => '4',
            'vUnCom' => '55.00',
            'vProd' => '55.00',
            'cEANTrib' => '',
            'uTrib' => 'Lt',
            'qTrib' => '120',
            'vUnTrib' => '7.00',
            'vFrete' => '',
            'vSeg' => '',
            'vDesc' => '',
            'vOutro' => '',
            'indTot' => '1',
            'xPed' => '16',
            'nItemPed' => '1',
            'nFCI' => '');
//produtos 2
        $aP[] = array(
            'nItem' => 2,
            'cProd' => '56',
            'cEAN' => '7896030801822',
            'xProd' => 'Detergente de parabrisa',
            'NCM' => '39241000',
            'EXTIPI' => '',
            'CFOP' => '5102',
            'uCom' => 'S/U',
            'qCom' => '2',

resources/views/jobs/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="card card-block mt-1">
                    <h3 class="card-title">Serviços Executados</h3>

                    <p>
                        <a href="{{ route('jobs.create') }}">Executar serviço</a>
                    </p>

                    <div class="card-text">
                        @if ($jobs->count())
                            <table class="table">
                                <thead>
                                <tr>
                                    <th>Serviço</th>
                                    <th>Preço</th>
                                    <th>Veículo</th>
                                    <th>Data de execução</th>
                                    <th>Ações</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach ($jobs as $job)
                                    <tr>
                                        <td>{{ $job->service->name }}</td>
                                        <td>R$ {{ $job->service->price }}</td>
                                        <td>{{ $job->vehicle->plate }}</td>
                                        <td>{{ $job->created_at->format('d/m/Y H:i') }}</td>
                                        <td>
                                            <a href="{{ route('jobs.show', $job) }}">
                                                Ver serviço
                                            </a>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        @else
                            <p class="p-3 text-xs-center">Nenhum serviço cadastrado ainda</p>
                        @endif

                        {{ $jobs->links('pagination::bootstrap-4') }}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/jobs/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="card card-block mt-1">
                    <h3 class="card-title">Serviço Executado: {{ $job->service->name }}</h3>

                    <p>
                        <a href="{{ route('jobs.index') }}">Ver serviços executados</a>
                    </p>

                    <div class="card-text">
                        <a class="btn btn-primary mb-1" href="https://docs.oracle.com/cd/E39557_01/doc.91/e51642/img/danfe_example_90_1.gif" download>Fazer download</a>
                        <a class="btn btn-primary mb-1" href="#">Enviar para cliente</a>
                        <a class="btn btn-primary mb-1" href="/jobs/{{ $job->id }}/xml">Baixar XML</a>
                        <br>
                       <img src="https://docs.oracle.com/cd/E39557_01/doc.91/e51642/img/danfe_example_90_1.gif" alt="">
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection