routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('/', 'PagesController@index');

Auth::routes();

Route::group(['middleware' => 'auth'], function () {
    Route::get('/dashboard', 'DashboardController@index');

    Route::get('jobs/{job}/xml', 'JobsController@showXml');
    Route::get('jobs/{job}/pdf', 'JobsController@showPdf');
    Route::resource('jobs', 'JobsController');

    Route::get('customers/{customer}/barcode', function (App\Customer $customer) {
        $barcodeOptions = [
            'text' => str_pad($customer->id, 12, '0', STR_PAD_LEFT),
            'barHeight' => 100,
            'barThickWidth' => 4,
            'barThinWidth' => 2,
        ];

        // No required options.
        $rendererOptions = [
            'barHeight' => 100,
        ];

        // Draw the barcode, capturing the resource:
        $renderer = \Zend\Barcode\Barcode::factory(
            'ean13',
            'image',
            $barcodeOptions,
            $rendererOptions
        );
        return new \Illuminate\Http\Response($renderer->render(), 200, ['Content-Type' => 'image/png']);
    });
    Route::resource('customers', 'CustomersController');
    Route::resource('vehicles', 'VehiclesController');
    Route::resource('services', 'ServicesController');
});

app/Customer.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Customer extends Model
{
    protected $fillable = [ 'name', 'email', 'document', 'address', 'phone', 'birthday' ];

    protected $dates = [ 'birthday' ];

    public function vehicles()
    {
        return $this->hasMany(Vehicle::class);
    }
}

app/Http/Controllers/CustomersController.php
<?php

namespace App\Http\Controllers;

use App\Customer;
use Illuminate\Http\Request;
use App\Http\Requests\StoreCustomerRequest;

class CustomersController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $customers = Customer::paginate();

        return view('customers.index')->withCustomers($customers);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('customers.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreCustomerRequest $request)
    {
        Customer::create($request->all());

        return redirect()->route('customers.index');
    }

    /**
     * Display the specified resource.
     *
     * @param Customer $customer
     * @return \Illuminate\Http\Response
     */
    public function show(Customer $customer)
    {
        return view('customers.show', compact('customer'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/customers/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="card card-block mt-1">
                    <h3 class="card-title">Novo Cliente</h3>

                    <p>
                        <a href="{{ route('customers.index') }}">Ver Clientes</a>
                    </p>

                    <div class="card-title row">
                        <form action="{{ route('customers.store') }}" method="post" class="col-md-6 offset-md-3">

                            {{ csrf_field() }}

                            <div class="form-group{{ $errors->has('name') ? ' has-danger' : '' }}">
                                <label for="name" class="col-form-label">Name</label>
                                <input type="text" id="name" name="name" class="form-control">
                                @if ($errors->has('name'))
                                    <span class="form-control-feedback">{{ $errors->first('name') }}</span>
                                @endif
                            </div>

                            <div class="form-group">
                                <label for="email">E-mail</label>
                                <input type="email" id="email" name="email" class="form-control">
                                @if ($errors->has('email'))
                                    <span class="help-block">{{ $errors->first('email') }}</span>
                                @endif
                            </div>

                            <div class="form-group">
                                <label for="document">CPF</label>
                                <input type="text" id="document" name="document" class="form-control" pattern="\d{3}\.\d{3}\.\d{3}-\d{2}" required>
                                @if ($errors->has('document'))
                                    <span class="form-control-feedback">{{ $errors->first('document') }}</span>
                                @endif
                            </div>

                            <div class="form-group">
                                <label for="address">Endereço</label>
                                <input type="text" id="address" name="address" class="form-control" required>
                            </div>

                            <div class="form-group">
                                <label for="phone">Telefone</label>
                                <input type="text" id="phone" name="phone" class="form-control" pattern="^(\(\d{2}\) \d{4,5}-\d{4})$" required>
                                <span class="help-block">(99) 99999-9999</span>
                            </div>

                            <div class="form-group">
                                <label for="birthday">Data de Nascimento</label>
                                <input type="date" id="birthday" name="birthday" class="form-control" required>
                            </div>

                            <button class="btn btn-default">Adicionar</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/customers/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="card card-block mt-1">
                    <h3 class="card-title">Clientes</h3>
                    
                    <p>
                        <a href="{{ route('customers.create') }}">Novo Cliente</a>
                    </p>

                    <div class="card-text">
                        @if ($customers->count())
                            <table class="table">
                                <thead>
                                <tr>
                                    <th>Nome</th>
                                    <th>E-mail</th>
                                    <th>Nascimento</th>
                                    <th>Cliente desde</th>
                                    <th>Ações</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach ($customers as $customer)
                                    <tr>
                                        <td>{{ $customer->name }}</td>
                                        <td>{{ $customer->email }}</td>
                                        <td>
                                            {{ $customer->birthday->format('d/m/Y') }}
                                            ({{ $customer->birthday->age }} anos)
                                        </td>
                                        <td>{{ $customer->created_at->diffForHumans() }}</td>
                                        <td>
                                            <a href="{{ route('customers.show', $customer) }}">
                                                Ver perfil
                                            </a>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        @else
                            <p class="p-3 text-xs-center">Nenhum cliente cadastrado ainda</p>
                        @endif

                        {{ $customers->links('pagination::bootstrap-4') }}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/customers/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12 mt-1">
                <div class="card card-block">
                    <h3 class="card-title">Cliente: {{ $customer->name }}</h3>

                    <div class="card-text">
                        <div class="row">
                            <div class="col-md-6">
                                <h4 class="mt-0">Dados</h4>

                                <dl>
                                    <dt>Nome</dt>
                                    <dd>{{ $customer->name }}</dd>

                                    <dt>E-mail</dt>
                                    <dd>{{ $customer->email }}</dd>

                                    <dt>CPF:</dt>
                                    <dd>{{ $customer->document }}</dd>

                                    <dt>Endereço</dt>
                                    <dd>{{ $customer->address }}</dd>

                                    <dt>Telefone</dt>
                                    <dd>{{ $customer->phone }}</dd>

                                    <dt>Nascimento</dt>
                                    <dd>
                                        {{ $customer->birthday->age }} anos - {{ $customer->birthday->format('d/m/Y') }}
                                    </dd>

                                    <dt>Cliente desde</dt>
                                    <dd>{{ $customer->created_at->diffForHumans() }}</dd>
                                </dl>
                            </div>
                            <div class="col-md-6">
                                <img src="https://api.qrserver.com/v1/create-qr-code/?size=150x150&data={{ route('customers.show', $customer) }}" alt="">
                            </div>
                        </div>

                        <h4>Veículos</h4>
                        <table class="table">
                            <thead>
                            <tr>
                                <th>Modelo</th>
                                <th>Placa</th>
                                <th>Ano</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach ($customer->vehicles as $vehicle)
                                <tr>
                                    <td>{{ $vehicle->model }}</td>
                                    <td>{{ $vehicle->plate }}</td>
                                    <td>{{ $vehicle->year }}</td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>

                        <h4>Lavagens</h4>
                        <table class="table">
                            <thead>
                            <tr>
                                <th>Carro</th>
                                <th>Serviço</th>
                                <th>Valor</th>
                                <th>Data</th>
                            </tr>
                            </thead>
                            <tbody>
                            <tr>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>
                            </tr>
                            </tbody>
                        </table>

                        <h4>Estacionamento</h4>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection